// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqRVJxYJs-21doZpSVBIyia2lk9s4snPY',
    appId: '1:387404596114:web:5932324eca02b04c7ef74b',
    messagingSenderId: '387404596114',
    projectId: 'bloodlinker-b8d91',
    authDomain: 'bloodlinker-b8d91.firebaseapp.com',
    storageBucket: 'bloodlinker-b8d91.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLyW9BBR_6MdVWapw9y0fJpTEk_eCLjQM',
    appId: '1:387404596114:android:db6f12eb3120a00a7ef74b',
    messagingSenderId: '387404596114',
    projectId: 'bloodlinker-b8d91',
    storageBucket: 'bloodlinker-b8d91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPdKee810OhXbq2B1kqY58RviGcq9AvyE',
    appId: '1:387404596114:ios:1c41b7ddfb6a417a7ef74b',
    messagingSenderId: '387404596114',
    projectId: 'bloodlinker-b8d91',
    storageBucket: 'bloodlinker-b8d91.firebasestorage.app',
    iosBundleId: 'com.example.bloodLinker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPdKee810OhXbq2B1kqY58RviGcq9AvyE',
    appId: '1:387404596114:ios:1c41b7ddfb6a417a7ef74b',
    messagingSenderId: '387404596114',
    projectId: 'bloodlinker-b8d91',
    storageBucket: 'bloodlinker-b8d91.firebasestorage.app',
    iosBundleId: 'com.example.bloodLinker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqRVJxYJs-21doZpSVBIyia2lk9s4snPY',
    appId: '1:387404596114:web:a2904140bcc9dcba7ef74b',
    messagingSenderId: '387404596114',
    projectId: 'bloodlinker-b8d91',
    authDomain: 'bloodlinker-b8d91.firebaseapp.com',
    storageBucket: 'bloodlinker-b8d91.firebasestorage.app',
  );

}